# Generated by Django 6.0 on 2026-01-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
